/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConversionProgress: typeof import('./../components/ConversionProgress.vue')['default']
    DropZone: typeof import('./../components/DropZone.vue')['default']
    FileList: typeof import('./../components/FileList.vue')['default']
    FileListEntry: typeof import('./../components/FileListEntry.vue')['default']
    FormatSelect: typeof import('./../components/FormatSelect.vue')['default']
    SolarAltArrowRightLinear: typeof import('~icons/solar/alt-arrow-right-linear')['default']
    SolarBlackHoleLinear: typeof import('~icons/solar/black-hole-linear')['default']
    SolarCheckSquareLinear: typeof import('~icons/solar/check-square-linear')['default']
    SolarCodeCircleLinear: typeof import('~icons/solar/code-circle-linear')['default']
    SolarFolderWithFilesLinear: typeof import('~icons/solar/folder-with-files-linear')['default']
    SolarListCrossMinimalisticLinear: typeof import('~icons/solar/list-cross-minimalistic-linear')['default']
    SolarMoonLinear: typeof import('~icons/solar/moon-linear')['default']
    SolarRestartLinear: typeof import('~icons/solar/restart-linear')['default']
    SolarShieldCrossLinear: typeof import('~icons/solar/shield-cross-linear')['default']
    SolarStopLinear: typeof import('~icons/solar/stop-linear')['default']
    SolarSun2Linear: typeof import('~icons/solar/sun2-linear')['default']
    SolarVerifiedCheckLinear: typeof import('~icons/solar/verified-check-linear')['default']
    SolarWallpaperLinear: typeof import('~icons/solar/wallpaper-linear')['default']
    Toolbar: typeof import('./../components/Toolbar.vue')['default']
  }
}
